name: Check code quality.
run-name: ${{ github.actor }} Check code quality.
on:
  push:
    branches:
      - "**"
      - "!main"
jobs:
  quality-check:
    name: Quality check
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Setup Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"
      - name: Install dependencies
        run: npm i
      - name: Run eslint
        run: npm run lint
      - name: Run prettier:check
        run: npm run prettier:check
      - name: Run test
        run: npm run test:coverage
      - name: Coveralls
        uses: coverallsapp/github-action@v2
